import { Basemap } from './basemap';

export class Map2 extends Basemap {

  static TILEIMAGES = [
    "ZeshioHexKitDemo_000.png",
    "ZeshioHexKitDemo_001.png",
    "ZeshioHexKitDemo_002.png",
    "ZeshioHexKitDemo_003.png",
    "ZeshioHexKitDemo_004.png",
    "ZeshioHexKitDemo_005.png",
    "ZeshioHexKitDemo_006.png",
    "ZeshioHexKitDemo_007.png",
    "ZeshioHexKitDemo_008.png",
    "ZeshioHexKitDemo_009.png",
    "ZeshioHexKitDemo_010.png",
    "ZeshioHexKitDemo_011.png",
    "ZeshioHexKitDemo_012.png",
    "ZeshioHexKitDemo_013.png",
    "ZeshioHexKitDemo_014.png",
    "ZeshioHexKitDemo_015.png",
    "ZeshioHexKitDemo_016.png",
    "ZeshioHexKitDemo_017.png",
    "ZeshioHexKitDemo_018.png",
    "ZeshioHexKitDemo_019.png",
    "ZeshioHexKitDemo_020.png",
    "ZeshioHexKitDemo_021.png",
    "ZeshioHexKitDemo_022.png",
    "ZeshioHexKitDemo_023.png",
    "ZeshioHexKitDemo_024.png",
    "ZeshioHexKitDemo_025.png",
    "ZeshioHexKitDemo_026.png",
    "ZeshioHexKitDemo_027.png",
    "ZeshioHexKitDemo_028.png",
    "ZeshioHexKitDemo_029.png",
    "ZeshioHexKitDemo_030.png",
    "ZeshioHexKitDemo_031.png",
    "ZeshioHexKitDemo_032.png",
    "ZeshioHexKitDemo_033.png",
    "ZeshioHexKitDemo_034.png",
    "ZeshioHexKitDemo_035.png",
    "ZeshioHexKitDemo_036.png",
    "ZeshioHexKitDemo_037.png",
    "ZeshioHexKitDemo_038.png",
    "ZeshioHexKitDemo_039.png",
    "ZeshioHexKitDemo_040.png",
    "ZeshioHexKitDemo_041.png",
    "ZeshioHexKitDemo_042.png",
    "ZeshioHexKitDemo_043.png",
    "ZeshioHexKitDemo_044.png",
    "ZeshioHexKitDemo_045.png",
    "ZeshioHexKitDemo_046.png",
    "ZeshioHexKitDemo_047.png",
    "ZeshioHexKitDemo_048.png",
    "ZeshioHexKitDemo_049.png",
    "ZeshioHexKitDemo_050.png",
    "ZeshioHexKitDemo_051.png",
    "ZeshioHexKitDemo_052.png",
    "ZeshioHexKitDemo_053.png",
    "ZeshioHexKitDemo_054.png",
    "ZeshioHexKitDemo_055.png",
    "ZeshioHexKitDemo_056.png",
    "ZeshioHexKitDemo_057.png",
    "ZeshioHexKitDemo_058.png",
    "ZeshioHexKitDemo_059.png",
    "ZeshioHexKitDemo_060.png",
    "ZeshioHexKitDemo_061.png",
    "ZeshioHexKitDemo_062.png",
    "ZeshioHexKitDemo_063.png",
    "ZeshioHexKitDemo_064.png",
    "ZeshioHexKitDemo_065.png",
    "ZeshioHexKitDemo_066.png",
    "ZeshioHexKitDemo_067.png",
    "ZeshioHexKitDemo_068.png",
    "ZeshioHexKitDemo_069.png",
    "ZeshioHexKitDemo_070.png",
    "ZeshioHexKitDemo_071.png",
    "ZeshioHexKitDemo_072.png",
    "ZeshioHexKitDemo_073.png",
    "ZeshioHexKitDemo_074.png",
    "ZeshioHexKitDemo_075.png",
    "ZeshioHexKitDemo_076.png",
    "ZeshioHexKitDemo_077.png",
    "ZeshioHexKitDemo_078.png",
    "ZeshioHexKitDemo_079.png",
    "ZeshioHexKitDemo_080.png",
    "ZeshioHexKitDemo_081.png",
    "ZeshioHexKitDemo_082.png",
    "ZeshioHexKitDemo_083.png",
    "ZeshioHexKitDemo_084.png",
    "ZeshioHexKitDemo_085.png",
    "ZeshioHexKitDemo_086.png",
    "ZeshioHexKitDemo_087.png",
    "ZeshioHexKitDemo_088.png",
    "ZeshioHexKitDemo_089.png",
    "ZeshioHexKitDemo_090.png",
    "ZeshioHexKitDemo_091.png",
    "ZeshioHexKitDemo_092.png",
    "ZeshioHexKitDemo_093.png",
    "ZeshioHexKitDemo_094.png",
    "ZeshioHexKitDemo_095.png",
    "ZeshioHexKitDemo_096.png",
    "ZeshioHexKitDemo_097.png",
    "ZeshioHexKitDemo_098.png",
    "ZeshioHexKitDemo_099.png",
    "ZeshioHexKitDemo_100.png",
    "ZeshioHexKitDemo_101.png",
    "ZeshioHexKitDemo_102.png",
    "ZeshioHexKitDemo_103.png",
    "ZeshioHexKitDemo_104.png",
    "ZeshioHexKitDemo_105.png",
    "ZeshioHexKitDemo_106.png",
    "ZeshioHexKitDemo_107.png",
    "ZeshioHexKitDemo_108.png",
    "ZeshioHexKitDemo_109.png",
    "ZeshioHexKitDemo_110.png",
    "ZeshioHexKitDemo_111.png",
    "ZeshioHexKitDemo_112.png",
    "ZeshioHexKitDemo_113.png",
    "ZeshioHexKitDemo_114.png",
    "ZeshioHexKitDemo_115.png",
    "ZeshioHexKitDemo_116.png",
    "ZeshioHexKitDemo_117.png",
    "ZeshioHexKitDemo_118.png",
    "ZeshioHexKitDemo_119.png",
    "ZeshioHexKitDemo_120.png"
  ];

  static MAP = [
    [
      null,
      null,
      null,
      null,
      {id: 36,col: 4,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 45,col: 5,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 54,col: 6,row: 0, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 63,col: 7,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 72,col: 8,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      null,
      null,
      {id: 28,col: 3,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 37,col: 4,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 46,col: 5,row: 1, t:103, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 55,col: 6,row: 1, t:108, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 64,col: 7,row: 1, t: [96,89], path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 73,col: 8,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      null,
      {id: 20,col: 2,row: 2, t: 54, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 29,col: 3,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 38,col: 4,row: 2, t:106, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 47,col: 5,row: 2, t:[96,71], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 56,col: 6,row: 2, t:108, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 65,col: 7,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 74,col: 8,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      {id: 12,col: 1,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 21,col: 2,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 30,col: 3,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 39,col: 4,row: 3, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 48,col: 5,row: 3, t:105, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 57,col: 6,row: 3, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 66,col: 7,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 75,col: 8,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      {id: 4, col: 0,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 13,col: 1,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 22,col: 2,row: 4, t: 63, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 31,col: 3,row: 4, t: 64, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 40,col: 4,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 49,col: 5,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 58,col: 6,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 67,col: 7,row: 4, t:[97,120], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 76,col: 8,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      {id: 5, col: 0,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 14,col: 1,row: 5, t: 49, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 23,col: 2,row: 5, t:  2, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 32,col: 3,row: 5, t: 50, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 41,col: 4,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 50,col: 5,row: 5, t: [97,118], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 59,col: 6,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 68,col: 7,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null
    ],
    [
      {id: 6, col: 0,row: 6, t: 48, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 15,col: 1,row: 6, t:  3, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 24,col: 2,row: 6, t:  1, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 33,col: 3,row: 6, t: 21, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 42,col: 4,row: 6, t:[106,112], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 51,col: 5,row: 6, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 60,col: 6,row: 6, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null
    ],
    [
      {id: 7, col: 0,row: 7, t: 45, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 16,col: 1,row: 7, t: 22, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 25,col: 2,row: 7, t: 25, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 34,col: 3,row: 7, t:105, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 43,col: 4,row: 7, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 52,col: 5,row: 7, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null,
      null
    ],
    [
      {id: 8, col: 0,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 17,col: 1,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 26,col: 2,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 35,col: 3,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 44,col: 4,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null,
      null,
      null
    ]
  ];

  }
