import { Basemap } from './basemap';

export class Map2 extends Basemap {

  static TILEIMAGES = [
    "/images/hex/ZeshioHexKitDemo_000.png",
    "/images/hex/ZeshioHexKitDemo_001.png",
    "/images/hex/ZeshioHexKitDemo_002.png",
    "/images/hex/ZeshioHexKitDemo_003.png",
    "/images/hex/ZeshioHexKitDemo_004.png",
    "/images/hex/ZeshioHexKitDemo_005.png",
    "/images/hex/ZeshioHexKitDemo_006.png",
    "/images/hex/ZeshioHexKitDemo_007.png",
    "/images/hex/ZeshioHexKitDemo_008.png",
    "/images/hex/ZeshioHexKitDemo_009.png",
    "/images/hex/ZeshioHexKitDemo_010.png",
    "/images/hex/ZeshioHexKitDemo_011.png",
    "/images/hex/ZeshioHexKitDemo_012.png",
    "/images/hex/ZeshioHexKitDemo_013.png",
    "/images/hex/ZeshioHexKitDemo_014.png",
    "/images/hex/ZeshioHexKitDemo_015.png",
    "/images/hex/ZeshioHexKitDemo_016.png",
    "/images/hex/ZeshioHexKitDemo_017.png",
    "/images/hex/ZeshioHexKitDemo_018.png",
    "/images/hex/ZeshioHexKitDemo_019.png",
    "/images/hex/ZeshioHexKitDemo_020.png",
    "/images/hex/ZeshioHexKitDemo_021.png",
    "/images/hex/ZeshioHexKitDemo_022.png",
    "/images/hex/ZeshioHexKitDemo_023.png",
    "/images/hex/ZeshioHexKitDemo_024.png",
    "/images/hex/ZeshioHexKitDemo_025.png",
    "/images/hex/ZeshioHexKitDemo_026.png",
    "/images/hex/ZeshioHexKitDemo_027.png",
    "/images/hex/ZeshioHexKitDemo_028.png",
    "/images/hex/ZeshioHexKitDemo_029.png",
    "/images/hex/ZeshioHexKitDemo_030.png",
    "/images/hex/ZeshioHexKitDemo_031.png",
    "/images/hex/ZeshioHexKitDemo_032.png",
    "/images/hex/ZeshioHexKitDemo_033.png",
    "/images/hex/ZeshioHexKitDemo_034.png",
    "/images/hex/ZeshioHexKitDemo_035.png",
    "/images/hex/ZeshioHexKitDemo_036.png",
    "/images/hex/ZeshioHexKitDemo_037.png",
    "/images/hex/ZeshioHexKitDemo_038.png",
    "/images/hex/ZeshioHexKitDemo_039.png",
    "/images/hex/ZeshioHexKitDemo_040.png",
    "/images/hex/ZeshioHexKitDemo_041.png",
    "/images/hex/ZeshioHexKitDemo_042.png",
    "/images/hex/ZeshioHexKitDemo_043.png",
    "/images/hex/ZeshioHexKitDemo_044.png",
    "/images/hex/ZeshioHexKitDemo_045.png",
    "/images/hex/ZeshioHexKitDemo_046.png",
    "/images/hex/ZeshioHexKitDemo_047.png",
    "/images/hex/ZeshioHexKitDemo_048.png",
    "/images/hex/ZeshioHexKitDemo_049.png",
    "/images/hex/ZeshioHexKitDemo_050.png",
    "/images/hex/ZeshioHexKitDemo_051.png",
    "/images/hex/ZeshioHexKitDemo_052.png",
    "/images/hex/ZeshioHexKitDemo_053.png",
    "/images/hex/ZeshioHexKitDemo_054.png",
    "/images/hex/ZeshioHexKitDemo_055.png",
    "/images/hex/ZeshioHexKitDemo_056.png",
    "/images/hex/ZeshioHexKitDemo_057.png",
    "/images/hex/ZeshioHexKitDemo_058.png",
    "/images/hex/ZeshioHexKitDemo_059.png",
    "/images/hex/ZeshioHexKitDemo_060.png",
    "/images/hex/ZeshioHexKitDemo_061.png",
    "/images/hex/ZeshioHexKitDemo_062.png",
    "/images/hex/ZeshioHexKitDemo_063.png",
    "/images/hex/ZeshioHexKitDemo_064.png",
    "/images/hex/ZeshioHexKitDemo_065.png",
    "/images/hex/ZeshioHexKitDemo_066.png",
    "/images/hex/ZeshioHexKitDemo_067.png",
    "/images/hex/ZeshioHexKitDemo_068.png",
    "/images/hex/ZeshioHexKitDemo_069.png",
    "/images/hex/ZeshioHexKitDemo_070.png",
    "/images/hex/ZeshioHexKitDemo_071.png",
    "/images/hex/ZeshioHexKitDemo_072.png",
    "/images/hex/ZeshioHexKitDemo_073.png",
    "/images/hex/ZeshioHexKitDemo_074.png",
    "/images/hex/ZeshioHexKitDemo_075.png",
    "/images/hex/ZeshioHexKitDemo_076.png",
    "/images/hex/ZeshioHexKitDemo_077.png",
    "/images/hex/ZeshioHexKitDemo_078.png",
    "/images/hex/ZeshioHexKitDemo_079.png",
    "/images/hex/ZeshioHexKitDemo_080.png",
    "/images/hex/ZeshioHexKitDemo_081.png",
    "/images/hex/ZeshioHexKitDemo_082.png",
    "/images/hex/ZeshioHexKitDemo_083.png",
    "/images/hex/ZeshioHexKitDemo_084.png",
    "/images/hex/ZeshioHexKitDemo_085.png",
    "/images/hex/ZeshioHexKitDemo_086.png",
    "/images/hex/ZeshioHexKitDemo_087.png",
    "/images/hex/ZeshioHexKitDemo_088.png",
    "/images/hex/ZeshioHexKitDemo_089.png",
    "/images/hex/ZeshioHexKitDemo_090.png",
    "/images/hex/ZeshioHexKitDemo_091.png",
    "/images/hex/ZeshioHexKitDemo_092.png",
    "/images/hex/ZeshioHexKitDemo_093.png",
    "/images/hex/ZeshioHexKitDemo_094.png",
    "/images/hex/ZeshioHexKitDemo_095.png",
    "/images/hex/ZeshioHexKitDemo_096.png",
    "/images/hex/ZeshioHexKitDemo_097.png",
    "/images/hex/ZeshioHexKitDemo_098.png",
    "/images/hex/ZeshioHexKitDemo_099.png",
    "/images/hex/ZeshioHexKitDemo_100.png",
    "/images/hex/ZeshioHexKitDemo_101.png",
    "/images/hex/ZeshioHexKitDemo_102.png",
    "/images/hex/ZeshioHexKitDemo_103.png",
    "/images/hex/ZeshioHexKitDemo_104.png",
    "/images/hex/ZeshioHexKitDemo_105.png",
    "/images/hex/ZeshioHexKitDemo_106.png",
    "/images/hex/ZeshioHexKitDemo_107.png",
    "/images/hex/ZeshioHexKitDemo_108.png",
    "/images/hex/ZeshioHexKitDemo_109.png",
    "/images/hex/ZeshioHexKitDemo_110.png",
    "/images/hex/ZeshioHexKitDemo_111.png",
    "/images/hex/ZeshioHexKitDemo_112.png",
    "/images/hex/ZeshioHexKitDemo_113.png",
    "/images/hex/ZeshioHexKitDemo_114.png",
    "/images/hex/ZeshioHexKitDemo_115.png",
    "/images/hex/ZeshioHexKitDemo_116.png",
    "/images/hex/ZeshioHexKitDemo_117.png",
    "/images/hex/ZeshioHexKitDemo_118.png",
    "/images/hex/ZeshioHexKitDemo_119.png",
    "/images/hex/ZeshioHexKitDemo_120.png"
  ];

  static MAP = [
    [
      null,
      null,
      null,
      null,
      {id: 36,col: 4,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 45,col: 5,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 54,col: 6,row: 0, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 63,col: 7,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 72,col: 8,row: 0, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      null,
      null,
      {id: 28,col: 3,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 37,col: 4,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 46,col: 5,row: 1, t:103, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 55,col: 6,row: 1, t:108, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 64,col: 7,row: 1, t: [96,89], path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 73,col: 8,row: 1, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      null,
      {id: 20,col: 2,row: 2, t: 54, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 29,col: 3,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 38,col: 4,row: 2, t:106, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 47,col: 5,row: 2, t:[96,71], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 56,col: 6,row: 2, t:108, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 65,col: 7,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 74,col: 8,row: 2, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      null,
      {id: 12,col: 1,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 21,col: 2,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 30,col: 3,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 39,col: 4,row: 3, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 48,col: 5,row: 3, t:105, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 57,col: 6,row: 3, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 66,col: 7,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 75,col: 8,row: 3, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      {id: 4, col: 0,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 13,col: 1,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 22,col: 2,row: 4, t: 63, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 31,col: 3,row: 4, t: 64, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 40,col: 4,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 49,col: 5,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 58,col: 6,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 67,col: 7,row: 4, t:[97,120], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 76,col: 8,row: 4, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}}
    ],
    [
      {id: 5, col: 0,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 14,col: 1,row: 5, t: 49, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 23,col: 2,row: 5, t:  2, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 32,col: 3,row: 5, t: 50, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 41,col: 4,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 50,col: 5,row: 5, t: [97,118], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 59,col: 6,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 68,col: 7,row: 5, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null
    ],
    [
      {id: 6, col: 0,row: 6, t: 48, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 15,col: 1,row: 6, t:  3, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 24,col: 2,row: 6, t:  1, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 33,col: 3,row: 6, t: 21, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 42,col: 4,row: 6, t:[106,112], path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 51,col: 5,row: 6, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 60,col: 6,row: 6, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null
    ],
    [
      {id: 7, col: 0,row: 7, t: 45, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 16,col: 1,row: 7, t: 22, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 25,col: 2,row: 7, t: 25, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 34,col: 3,row: 7, t:105, path: {f:0, g:0, h:0, w:1, visited:false, closed:false, parent:null}},
      {id: 43,col: 4,row: 7, t: 96, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 52,col: 5,row: 7, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null,
      null
    ],
    [
      {id: 8, col: 0,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 17,col: 1,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 26,col: 2,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 35,col: 3,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      {id: 44,col: 4,row: 8, t: 97, path: {f:0, g:0, h:0, w:0, visited:false, closed:false, parent:null}},
      null,
      null,
      null,
      null
    ]
  ];

  }
